- project:
    check:
      queue: core
      jobs:
        - linters
    gate:
      queue: core
      jobs:
        - linters
    release:
      jobs:
        - upload-pypi-sesheta
    kebechet-auto-gate:
      queue: core
      jobs:
        - linters
