- project:
    check:
      queue: thoth-station/user-api
      jobs:
        - linters
    gate:
      queue: thoth-station/user-api
      jobs:
        - linters
    release:
      jobs:
        - upload-pypi-sesheta
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: "https://paas.upshift.redhat.com/oapi/v1/namespaces/thoth-test-core/buildconfigs/user-api/webhooks/"
    kebechet-auto-gate:
      queue: thoth-station/user-api
      jobs:
        - linters
